### ISSUE TITLE
SDX-common is now separate from sdx-ops. Review required please.

### ISSUE THREAD

**Issue by tundish** [ONSdigital/sdx-common#1]
- I created a new _sdx-common_ repo.
- In Github, I imported the existing _sdx-ops_ repo to keep the history.
- Then removed files from each repo where not required.

However this all occured on the master branch, so no pull request is possible. This issue requests a code review.

**Comment by warrenbailey** [comment]
@necrophonic This repo needs a develop branch and an associated travis job

**Comment by warrenbailey** [comment]
I don't think the Apache 2 license is the correct one? Don't we use MIT?

**Comment by warrenbailey** [comment]
The description in setup.py is incorrect: 
"description="Operations scripts for SDX deployment and administration."

**Comment by warrenbailey** [comment]
The README file is RST and not MD, I thought convention in ONS was MD?

**Comment by warrenbailey** [comment]
Do we need the sdx directory? Could common be top level?

**Comment by warrenbailey** [comment]
Should processor.py be in here? I can only find it's usages in sdx-downstream-ctp

**Comment by warrenbailey** [comment]
How has the code from sdx-ops been removed without a PR? It seems to have vanished?

**Comment by warrenbailey** [comment]
I don't understand the survey.py file either, where is that used?

**Comment by warrenbailey** [comment]
Thanks for the responses, still need to correct the license though

**Comment by JamesGardiner** [comment]
Any chance of a makefile for automated building and testing?

**Comment by JamesGardiner** [comment]
Are we deploying docs to readthedocs yet?

**Comment by warrenbailey** [comment]
Can we close this issue?

**Comment by JamesGardiner** [comment]
Getting errors in sdx-compose related to this

```python
Traceback (most recent call last):
  File "/home/james/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/james/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/james/projects/sdx/sdx-ops/sdx/ops/configure.py", line 7, in <module>
    import sdx.common.cli
ModuleNotFoundError: No module named 'sdx.common'
```
Fixed by `cp`ing `common` back into the directory for now, but the build process needs looking at.
